#!/bin/sh

workdir=$(dirname $0)
passwd=$1
cd $workdir
echo "creating arkgate group"
groupadd arkgate
echo "done"

echo "Creating admin user..."
adduser -batch admin arkgate $passwd -unencrypted
echo "done"

cd /dev/
./MAKEDEV pppac1
./MAKEDEV pppac2
./MAKEDEV pppac3
./MAKEDEV pppac4
./MAKEDEV pppac5
./MAKEDEV pppac6
./MAKEDEV pppac7
echo "done"

cp -v ${workdir}/rc.arkgated /etc/rc.d/arkgated
cp -v ${workdir}/sysctl.conf /etc/

# Prompts for one setting on stdin/stdout, showing $2 as the default (press
# enter to accept it), and echoes the chosen value so callers can capture it
# via command substitution: value=$(prompt "Label" "default").
prompt() {
	label=$1
	def=$2
	if [ -n "$def" ]; then
		printf '%s [%s]: ' "$label" "$def" >&2
	else
		printf '%s: ' "$label" >&2
	fi
	read val
	if [ -z "$val" ]; then
		val=$def
	fi
	echo "$val"
}

appconfig="${workdir}/app.config"
genconfig=y
if [ -f "$appconfig" ]; then
	genconfig=$(prompt "$appconfig already exists. Regenerate it" "n")
fi

case "$genconfig" in
[Yy]*)
	echo ""
	echo "Configuring arkgated (app.config)."
	echo "Press enter to accept a default shown in [brackets]."
	srvcurl=$(prompt "Service manager url" "http://127.0.0.1/api/v1/")
	listenaddr=$(prompt "Network address to listen for IPC commands on" "0.0.0.0:8443")
	tlscert=$(prompt "Path to this daemon's TLS server certificate" "./rundir/arkgated.crt")
	tlskey=$(prompt "Path to this daemon's TLS server private key" "./rundir/arkgated.key")
	tlsclientca=$(prompt "Path to the CA certificate used to verify client (srvcman) certificates" "./rundir/ca.crt")
	creds=$(prompt "Basic auth api creds" "./rundir/")
	rundir=$(prompt "Path to rundir" "./rundir/")
	maxbuff=$(prompt "Max buffer size" "1024")

	cat >"$appconfig" <<-EOF
	# arkgated config file - one "key=value" per line, "#" starts a comment.
	# Generated by configure.sh; matches the -flag names in main.go, see
	# there for what each setting does.
	srvcurl=${srvcurl}
	listenaddr=${listenaddr}
	tlscert=${tlscert}
	tlskey=${tlskey}
	tlsclientca=${tlsclientca}
	creds=${creds}
	rundir=${rundir}
	maxbuff=${maxbuff}
	EOF
	chmod 600 "$appconfig"
	echo "Wrote $appconfig"
	;;
*)
	echo "Skipping app.config generation."
	;;
esac
